site_name: Tokamak
site_description: An HTTP router for Python projects based on radix trees.

theme:
    name: 'gitbook'
    highlightjs: true
    hljs_style: 'solarized-light'

repo_name: erewok/tokamak
repo_url: https://github.com/erewok/tokamak
edit_uri: ""

nav:
    - Radix Tree: 'radix_tree.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - mkautodoc

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'
