[tool.poetry]
name = "tokamak"
version = "0.1.0"
description = "HTTP Router based on radix trees"
authors = ["Erik Aker <eraker@gmail.com>"]
license = "BSD3"

[tool.poetry.dependencies]
python = "^3.10"
trio = "^0.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
