[tool.poetry]
name = "tokamak"
version = "0.3.0"
description = "HTTP Router based on radix trees"
authors = ["Erik Aker <eraker@gmail.com>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.9"
hypercorn = { version = "^0.13.2", optional = true }
trio = { version = "^0.20.0", optional = true }

[tool.poetry.dev-dependencies]
black = "^22.1.0"
hypothesis = "^6.39.4"
isort = "^5.10.1"
mypy = "^0.941"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-pycodestyle = "^2.3.0"
pytest-mypy = "^0.9.1"
twine = "^3.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
web = ["trio"]
examples = ["hypercorn"]
full = ["hypercorn", "trio"]
