[tool.poetry]
name = "tokamak"
version = "0.1.0"
description = "HTTP Router based on radix trees"
authors = ["Erik Aker <eraker@gmail.com>"]
license = "BSD3"

[tool.poetry.dependencies]
python = "^3.10"
trio = "^0.19.0"

[tool.poetry.dev-dependencies]
attrs = "^20.1.0"
black = "^20.8b1"
coverage = "^5.2.1"
flake8 = "^3.8.3"
hypothesis = "^5.35.3"
isort = "^5.5.2"
mypy = "^0.910"
mypy-extensions = "^0.4.3"
py = "^1.9.0"
pycodestyle = "^2.6.0"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pytest-flake8 = "^1.0.6"
pytest-mypy = "^0.7.0"
twine = "^3.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
